global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/c2058391-210e-4b49-9243-2fd8b01774f1'
          send_resolved: false