global:
  scrape_interval: 5s

rule_files:
  - rules.yml
alerting:
  alertmanagers:
  - static_configs:
    - targets: ["your.ip.here:9093"]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["your.ip.here:9090"]

  - job_name: 'node-exporter'
    static_configs:
      - targets: ["your.ip.here:9100"]

  - job_name: simple_server
    static_configs:
      - targets: ["your.ip.here:8090"]

  - job_name: app-py
    static_configs:
      - targets: ["your.ip.here:3001"]